# Generated by Django 2.2 on 2021-07-02 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_pormo_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pormo_code',
            new_name='promo_code',
        ),
    ]
